import { buildParseAcmeOrderEnrichPrompt } from './buildPrompt'

describe('buildParseAcmeOrderEnrichPrompt', () => {
    it('requires chain-of-reasoning markdown then fenced json, and retains compatibility contract', () => {
        const { invariantPrefix, dynamicSuffix } = buildParseAcmeOrderEnrichPrompt('order rope')
        expect(invariantPrefix).toContain('Classify order type')
        expect(invariantPrefix).toContain('two steps with different rules')
        expect(invariantPrefix).toContain('Enhance (JSON final)')
        expect(invariantPrefix).toContain('Correctable user error')
        expect(invariantPrefix).toContain('Cartoon physics')
        expect(invariantPrefix.indexOf('Correctable user error')).toBeLessThan(invariantPrefix.indexOf('Cartoon physics modifier'))
        expect(invariantPrefix.indexOf('Cartoon physics modifier')).toBeLessThan(invariantPrefix.indexOf('Primary category'))
        expect(invariantPrefix).toContain('language tag **json**')
        expect(invariantPrefix).toContain('**`trope`** is an allowlist field')
        expect(invariantPrefix).not.toContain('### Flat modification tags')
        expect(invariantPrefix).not.toContain('### Generative roles')
        expect(invariantPrefix).not.toContain('### Structural roles')
        expect(invariantPrefix).toContain('emit only **`Contraption`**, **`Distraction`**, **`Disadvantage`**, or **`Finishing Move`**')
        expect(invariantPrefix).toContain('tropeAffinities')
        expect(invariantPrefix).toContain('tropeAffinitiesFailed')
        expect(invariantPrefix).toContain('Step 1 trope anchor — Finishing Move')
        expect(invariantPrefix).toContain('Is this the thing the Coyote intends to be the last thing the Road Runner experiences?')
        expect(invariantPrefix).toContain('Contraption payload exclusion')
        expect(invariantPrefix).toContain('Dual-use handling')
        expect(invariantPrefix).toContain('knockout gas canister = payload')
        expect(invariantPrefix).toContain('grand piano dropped on Road Runner = payload')
        expect(invariantPrefix).toContain('For Step 1 lines classified as **Phenomenon**')
        expect(invariantPrefix).toContain('"pocket avalanche trigger" produces an avalanche')
        expect(invariantPrefix).toContain('Legacy compatibility placeholders')
        expect(invariantPrefix).toContain('affinitiesFailed')
        expect(invariantPrefix).not.toContain('skill check')
        expect(invariantPrefix).toContain('stableKey')
        expect(invariantPrefix).toContain('constructed-')
        expect(invariantPrefix).toContain('Do not treat a leading order verb as a line item')
        expect(invariantPrefix).toContain('Multi-command phrasing')
        expect(invariantPrefix).toContain('order glue and springs')
        expect(invariantPrefix).toContain('exactly two lines')
        expect(dynamicSuffix).toContain('order rope')
        expect(dynamicSuffix).toContain('Player command')
        expect(dynamicSuffix).toContain('Coyote-wide stable keys already in use')
        expect(dynamicSuffix).toContain('(none)')
    })

    it('lists occupied stable keys in dynamicSuffix after dedupe and sort', () => {
        const { dynamicSuffix } = buildParseAcmeOrderEnrichPrompt('buy widget', {
            occupiedStableKeys: ['zebra', 'alpha', 'alpha', 'beta'],
        })
        expect(dynamicSuffix).toContain('- alpha')
        expect(dynamicSuffix).toContain('- beta')
        expect(dynamicSuffix).toContain('- zebra')
        expect(dynamicSuffix.indexOf('- alpha')).toBeLessThan(dynamicSuffix.indexOf('- beta'))
        expect(dynamicSuffix.indexOf('- beta')).toBeLessThan(dynamicSuffix.indexOf('- zebra'))
    })
})
