AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  burnedover-mush-permanents-table

  SAM Template for the static DynamoDB storage associated with burnedover-mush.

Parameters:
  TablePrefix:
    Type: String
    Default: 'burnedover'
    Description: (Required) The name of the new DynamoDB to store connection identifiers for each connected clients. Minimum 3 characters
    MinLength: 3
    MaxLength: 50
    AllowedPattern: ^[A-Za-z_]+$
    ConstraintDescription: 'Required. Can be characters and underscore only. No numbers or special characters allowed.'

Resources:
    PermanentsTable:
        Type: AWS::DynamoDB::Table
        Properties:
          AttributeDefinitions:
            - AttributeName: "permanentId"
              AttributeType: "S"
            - AttributeName: "parentId"
              AttributeType: "S"
            - AttributeName: "fromRoomId"
              AttributeType: "S"
          BillingMode: "PAY_PER_REQUEST"
          KeySchema:
            - AttributeName: "permanentId"
              KeyType: "HASH"
          GlobalSecondaryIndexes:
            - IndexName: fromRoomIndex
              KeySchema:
                - AttributeName: fromRoomId
                  KeyType: HASH
              Projection:
                NonKeyAttributes:
                  - name
                  - parentId
                  - ancestry
                ProjectionType: INCLUDE
            - IndexName: parentIndex
              KeySchema:
                - AttributeName: parentId
                  KeyType: HASH
              Projection:
                ProjectionType: ALL
          TableName: !Sub '${TablePrefix}_permanents'
    CharactersTable:
        Type: AWS::DynamoDB::Table
        Properties:
          AttributeDefinitions:
            - AttributeName: "CharacterId"
              AttributeType: "S"
            - AttributeName: "PlayerName"
              AttributeType: "S"
            - AttributeName: "Name"
              AttributeType: "S"
          BillingMode: "PAY_PER_REQUEST"
          KeySchema:
            - AttributeName: "CharacterId"
              KeyType: "HASH"
          GlobalSecondaryIndexes:
            - IndexName: PlayerAndNameIndex
              KeySchema:
                - AttributeName: "PlayerName"
                  KeyType: "HASH"
                - AttributeName: "Name"
                  KeyType: "RANGE"
              Projection:
                ProjectionType: ALL
          TableName: !Sub '${TablePrefix}_characters'
    UserPool:
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: !Sub ${TablePrefix}-user-UserPool
        AutoVerifiedAttributes:
          - email
        MfaConfiguration: "OFF"
        AccountRecoverySetting:
          RecoveryMechanisms:
            - Name: verified_email
              Priority: 1
        EmailVerificationSubject: Welcome to BurnedOverMUSH
        EmailVerificationMessage: >
            Thank you for signing up for BurnedOverMUSH.  Here is your verification code (the system will ask for it): {####}
        Schema:
          - Name: email
            AttributeDataType: String
            Mutable: false
            Required: true
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: !Sub ${TablePrefix}-client
        GenerateSecret: false
        UserPoolId: !Ref UserPool
        AllowedOAuthFlows:
          - code
        AllowedOAuthFlowsUserPoolClient: true
        AllowedOAuthScopes:
          - email
          - openid
          - profile
          - aws.cognito.signin.user.admin
        ExplicitAuthFlows:
          - ALLOW_REFRESH_TOKEN_AUTH
          - ALLOW_USER_SRP_AUTH
        CallbackURLs:
          - http://localhost:3000
    UserPoolDomain:
      Type: AWS::Cognito::UserPoolDomain
      Properties:
        UserPoolId: !Ref UserPool
        Domain: !Sub ${TablePrefix}-auth

Outputs:
    TablePrefix:
        Description: The prefix with which tables should begin.
        Value: !Sub ${TablePrefix}
        Export:
            Name: !Sub "${AWS::StackName}-TablePrefix"

    PermanentsArn:
        Description: The Arn of the permanents table
        Value: !GetAtt "PermanentsTable.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-PermanentsArn"

    CharactersArn:
        Description: The Arn of the characters table
        Value: !GetAtt "CharactersTable.Arn"
        Export:
            Name: !Sub "${AWS::StackName}-CharactersArn"

    UserPoolClient:
        Description: The client ID for the player user pool
        Value: !Ref UserPoolClient
        Export:
          Name: !Sub "${AWS::StackName}-UserPoolClient"

    UserPoolId:
        Description: The internal ID for the player user pool
        Value: !Ref UserPool
        Export:
          Name: !Sub "${AWS::StackName}-UserPoolId"
