export const onboardingCheckpointSequence = [
    'navigateSettings',
    'navigateHome',
    'navigateKnowledge',
    'knowledgeDetail',
    'closeTab',
    'navigatePlay',
    'commandMode',
    'sayMode',
    'narrateMode',
    'OOCMode',
    'featureLink',
    'exitLink',
    'actionLink',
    'navigateHomeInPlay',
    'navigateLibrary',
    'createAsset',
    'nameAsset',
    'addRoom',
    'navigateRoom',
    'nameRoom',
    'describeRoom',
    'navigatePlayWithAsset',
    'importRoom',
    'navigateAssetWithImport',
    'addExit',
    'addExitBack',
    'saveAsset',
    'navigateLibraryAfterAsset',
    'editCharacter',
    'editCharacterAssets',
    'saveCharacter',
    'navigatePlayWithPersonalRoom',
    'navigatePersonalRoom',
    'closeOnboarding'
] as const

export type OnboardingKey = typeof onboardingCheckpointSequence[number]
