import { CANONICAL_TROPE_ORDER } from '@tonylb/mtw-interfaces/ts/coyotePhasePlan'
import type { CoyotePromptParts } from '../promptTypes'
import type { CombineCandidateOutputReturn } from '../candidates/combineCandidateOutput'
import { serializePlanSelectCandidateInput } from '../candidates/combineCandidateOutput'
import {
    COYOTE_HYPOTHESIS_CARTOON_OPPORTUNITY_LINES,
    COYOTE_HYPOTHESIS_WORLD_TOPOLOGY_LINES,
    coyoteSeamRoomMappingLines,
} from '../coyoteHypothesisPromptShared'
import {
    MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX,
    PLAN_SELECT_OUTPUT_JSON_KEYS,
} from './parsePlanSelectOutput'
import type { CoyoteRoomObjectsByRoom } from '../../../../utilities/coyoteRoomObjectSnapshot'

const PLAN_SELECT_TROPE_KEYS_LABEL = CANONICAL_TROPE_ORDER.map((t) => `**${t}**`).join(', ')

export type BuildPlanSelectPromptInput = {
    roomObjectsByRoom: CoyoteRoomObjectsByRoom
    combined: CombineCandidateOutputReturn
}

/** How to read the fenced JSON trope-candidates block in the dynamic tail. */
const PLAN_SELECT_COMBINED_JSON_SCHEMA_LINES = [
    '## Trope candidates JSON (input; how to read)',
    '- The **` ```json ` ** block in the dynamic section is **input only**: it is the complete,',
    '  authoritative list of **Stage One candidates** after parse and combine. **Schema version 4**',
    '  root keys: **`schemaVersion`**, **`candidates`**.',
    '- **`candidates`** is the exhaustive option set. You must **only** compare, score, and select',
    '  among these rows. **Do not** invent alternative plans, extra candidates, or substitute',
    '  paraphrases for new option ids.',
    '- Each candidate has **`candidateId`**, **`gimmick`**, **`executionSummary`**, **`tropeAssignments`**, and **`outliers`**.',
    '- **`gimmick`** is a **fixed short spine tag** from Stage One for that row (a few words typical); it labels that candidate\'s causal funnel.',
    '  You do **not** invent or rewrite **`gimmick`** during plan selection --- compare and choose among the supplied rows.',
    '- **`tropeAssignments`** is a **non-array object keyed by trope name** (allowed keys:',
    `  ${PLAN_SELECT_TROPE_KEYS_LABEL}); only present`,
    '  tropes appear as keys. When comparing candidates, read **Bait** as voluntary lure, **Misdirection**',
    '  as illusion or perception failure that spoils steering or control, **Disadvantage** as imposed impairment',
    '  independent of knowledge or consent.',
    '  Each value carries **`executionDetail`** (Stage One first-draft beat',
    '  detail) and **`members`**. Each member has **`stableKey`**, **`shortName`**, **`room`** (seam',
    '  label without the `ROOM#` prefix when known), and **`tropeFunction`** (that prop\'s',
    '  trope-local job in this candidate). Members may also include optional **`environmentAffordances`**:',
    '  an array of **`{ "object": <catalog scene object>, "roles": CoyoteTrope[] }`** from staged',
    '  object metadata (scene dependencies). Members may also include optional **`affordancesProvided`**:',
    '  an array of **`{ "object": string, "intended"?: true, "roles": CoyoteTrope[] }`** from staged',
    '  object metadata (explicit provided-affordance evidence for that prop).',
    '- **`outliers`** lists staged props not placed under any trope row for that candidate (server-derived),',
    '  each with **`stableKey`**, **`shortName`**, and **`room`** only (no **`tropeFunction`** on outliers),',
    '  and the same optional **`environmentAffordances`** / **`affordancesProvided`** shapes when present',
    '  on the staged object.',
    '- **`executionSummary`** states how that candidate frames the overall maneuver; **`gimmick`** names the row\'s spine;',
    '  member **`tropeFunction`** lines label each in-trope prop\'s intent. Use **`gimmick`** plus summary and tropes when',
    '  judging coherence and comparing **qualitatively different funnels**, not only trope permutations on the same spine;',
    '  treat outliers as membership evidence (which props are outside named trope beats in this candidate).',
    '- **Handoff JSON (materialized affordances).** In `selectedCandidate.tropeAssignments`, you may',
    `  append extra \`members\` rows whose \`stableKey\` begins with the literal prefix \`${MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX}\``,
    '  followed by a non-empty suffix (add numeric suffixes such as `affordance:boulder1` when multiple same-kind rows appear).',
    '  You may also **add** a **`Finishing Move`** trope key to **`tropeAssignments`** when Phase 1 requires it (valid **`executionDetail`** + **`members`**).',
    '  These rows are **not** staged room-object identities; they exist only inside the handoff. **`room`** on',
    '  such a row should match the seam label of the member or outlier row whose affordance evidence you used.',
    '  Supply **`shortName`** and **`tropeFunction`** as human-readable strings; optional **`environmentAffordances`** /',
    '  **`affordancesProvided`** use the same shapes as staged-backed members when present.',
    '- **Finishing Move guarantee carve-out:** Synthetic **`affordance:*`** rows (and a missing **`Finishing Move`** trope block, if added) required **only** to satisfy Phase 1 Sub-step A are **mandatory** when that sub-step demands them. They are **not** discretionary and **not** governed by the "clarify the maneuver" sentence below.',
    '- For **other** synthetic rows (not required by Sub-step A): only add them when they clarify the maneuver;',
    '  do not contradict the winning candidate\'s **`environmentAffordances`**, **`affordancesProvided`**, or **`tropeFunction`** text.',
    '- Choosing Coyote versus environment or provided finishing affordances must stay grounded in staged lists and the',
    '  candidate\'s **`executionSummary`** and trope fields --- no separate schema fork for Coyote.',
] as const

const PLAN_SELECTION_READING_RULES = [
    '## Reading the setup',
    '- Address the player in second person ("you") when describing what a plan would do.',
    '- Treat each **candidate** as one complete Coyote setup and maneuver path aimed at the Road Runner.',
    '- Use **stableKey**, **shortName**, and **room** from the JSON as ground truth for which prop is',
    '  where; use **tropeFunction** and **executionDetail** for how that candidate uses each in-trope prop.',
    '- Each candidate\'s **`gimmick`** is the fixed spine label for that row --- read it when comparing options',
    '  so rubric reasoning tracks **different causal funnels**, not only trope-slot differences.',
    '- When **`environmentAffordances`** appears on a member or outlier row, treat it as authored scene',
    '  dependency signal from staged metadata (what nearby terrain or catalog environment supports the beat).',
    '- When **`affordancesProvided`** appears on a member or outlier row, treat it as authored evidence',
    '  of what that staged prop is intended to supply; it complements **tropeFunction** but does not',
    '  replace it.',
    '- **Outliers** in the JSON are candidate-local: eligible props outside named trope rows for that',
    '  candidate only.',
    '- Member rows whose **`stableKey`** uses the materialized affordance prefix (see JSON section above) are',
    '  handoff-only annotations (required when Sub-step A mandates them, otherwise optional); read **`tropeFunction`**',
    '  and **`shortName`** on those rows like other members when reasoning about coverage for the handoff you emit.',
] as const

const PLAN_SELECTION_INTERNAL_PHASES_MULTI_CANDIDATE = [
    '## Internal phase order (single invocation; structured internals)',
    '- Keep one response, but execute these internal phases in order before finalizing output.',
    '- These phase artifacts are internal scaffolding for consistency and should not override output-format constraints.',
    '- The only **pipeline-consumed** artifact is the **final** trailing handoff **` ```json `** fence; Phase 1 materialization JSON is **visible scratchpad** you must write for reconciliation (see Task).',
    '- **Cleanup output vs wire naming.** Accumulate unresolved post-cleanup issues only in **`remainingPlanIssues`** during internal phases --- never build up something called **`planIssues`** for cleanup output (that name is reserved for downstream after deterministic rename). Input **`candidates[]`** rows do **not** carry a wire **`planIssues`** array; treat skeleton-derived gaps as facts, not as that array.',
    '- **Internal vs wire.** You may build a full **materialized candidate** (including `affordance:*` synthetic `members` rows) for **every** input option while comparing options. That full set exists **only inside this response** for rubric reasoning. It is **not** a second pipeline artifact. In the **trailing** handoff `json` fence, materialized `affordance:*` `members` appear **only** on **`selectedCandidate`**, not on non-winners --- match the trope candidates JSON section.',
    '',
    '### Phase 1 - cleanup: materialized candidate set (internal mini-schema)',
    '- **Primary output:** `materializedCandidates` --- an array with **exactly one** fully materialized candidate object per input `candidates[]` row, **in input order**, each with the **same top-level shape** as the input row: `candidateId`, `gimmick`, `executionSummary`, `tropeAssignments`, `outliers`. You **may** introduce a **`Finishing Move`** key under **`tropeAssignments`** when Sub-step A requires it (input rows may omit it).',
    `- **Goal:** For each option, **close resolvable gaps** so later scoring judges the plan at its **best achievable** form: promote affordance-backed staged props into the correct **trope** \`members\` rows (and add synthetic \`members\` whose \`stableKey\` uses the materialized prefix \`${MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX}\` when rules require), per the trope candidates JSON section.`,
    '- **Phase 1 is incomplete until written.** Emit this array as **real JSON** under **`## Materialized candidates (Phase 1)`** (Task section): one **` ```json `** block whose root object is **`{ "materializedCandidates": [ ... ] }`**. Phase 1 does **not** count as done until that fence exists. After it exists, treat it as the **source of truth** for candidate structure in Phase 2 / rubric --- do not reason from the raw input trope JSON alone.',
    '- **Soft verbosity caps** (prose only): after the Phase 1 JSON fence, keep per-candidate **annotation** bullets concise; at most **~12** non-empty bullets total across annotation lines for all candidates; at most **one sentence** per `tropeAssignments[*].executionDetail` rewrite when you edit **prose** unless the trope candidates JSON already implies longer beat text. **Carve-out:** the Phase 1 **` ```json `** body (full **`materializedCandidates`** objects) is **exempt** from "avoid repeating JSON" --- you **must** emit complete rows there.',
    '',
    '- **Per-issue cleanup process (sequential; mutual exclusivity).** Cleanup walks **each identified issue** for that candidate **in order** (from skeleton audit and internal FM checks). For **each** issue, follow **exactly one** exit --- remediation success and **`remainingPlanIssues`** listing are **not** independent outputs:',
    '  1. **Attempt remediation** using the rule that matches the issue: **Sub-step A** (Finishing Move guarantee; internal `MISSING_FINISHING_MOVE` control-flow only), or **Sub-step B** (`OUTLIER_PROP_UNACCOUNTED` promotion, `TROPE_FUNCTION_MISMATCH` alignment, `STRUCTURAL_CONTRADICTION` plurality reframe), as appropriate.',
    '  2. **If remediation succeeds:** apply it to the **materialized** candidate and proceed to the **next** issue. The issue is **consumed** --- it must **not** appear in **`remainingPlanIssues`**, in markdown, or in any other field.',
    '  3. **If remediation does not succeed:** add the issue to **`remainingPlanIssues`** and proceed to the **next** issue. **No partial remediation:** do not apply a half-fix for that issue and also list it --- choose **exit 2** (full apply) or **exit 3** (list unresolved) only.',
    '  - **`DIRECTION_AMBIGUOUS`** / **`ROLE_CONFLICT`:** **Skip step 1** --- cleanup does not remediate underspecification. **Go directly to step 3** when the issue still applies.',
    '  - **Branching invariant:** There is **no** path that both applies a fix in materialized structure **and** lists the **same** gap in **`remainingPlanIssues`**. When **Sub-step A** materializes **Finishing Move**, that **consumes** internal `MISSING_FINISHING_MOVE` at step 2 --- it **never** reaches step 3 (no extra suppression rule needed).',
    '',
    '- **Sub-step A - Finishing Move guarantee (required).** Phase 2 rubric judgment and downstream hops anchor on **Finishing Move** as a known quantity. A candidate that reaches Phase 2 **without** a **`Finishing Move`** entry in **`tropeAssignments`** containing **at least one** `members` row is **incomplete**, not merely unenhanced --- it cannot be scored on the same basis as a complete candidate. **Satisfaction rule:** **`tropeAssignments` must include `Finishing Move`** with **`members` length >= 1**, each row either a staged prop or a synthetic `affordance:*` row added here. **Invalid shortcuts:** "Contraption implicitly delivers the finish," **`executionSummary`** alone, or harm implied in prose **without** that trope row **do not** satisfy the guarantee. **`MISSING_FINISHING_MOVE`** is internal control-flow for step 1 only --- **never** a **`code`** in **`remainingPlanIssues`**.',
    '  - Internal control-flow only (never wire, never handoff): you may note `MISSING_FINISHING_MOVE` **while** cleanup still owes a **Finishing Move** trope block with **>= 1** member; **always resolve** it before Phase 2 so it **never** appears in the trailing fence.',
    '  - **FM guarantee vs discretionary materialization:** The trope candidates JSON section limits *discretionary* synthetic rows. **This sub-step overrides** that limit for Finishing Move: additions required here are **mandatory**, even when they would not otherwise "clarify" the maneuver under the optional-row rule.',
    '  - **You may add** a new **`Finishing Move`** key to **`tropeAssignments`** when the input row omitted it (supply **`executionDetail`** plus **`members`** per trope shape).',
    '  - **Resolution priority** (first match wins; stop when **`tropeAssignments.Finishing Move.members` has >= 1 row): (1) Input already has **`Finishing Move`** with **>= 1** staged **member** --- done (may still edit text under Sub-step B). (2) **`affordancesProvided`** on any staged **member** or **outlier** clearly indicates a finishing mechanism --- materialize into **`Finishing Move.members`**. (3) Candidate context implies **Coyote-as-payload** --- materialize `affordance:coyote` (or suffixed variant) under **`Finishing Move.members`**. (4) A **Contraption** member\'s **`environmentAffordances`** lists **Finishing Move** in **roles** --- materialize from those env refs into **`Finishing Move.members`**. (5) **Fallback:** `affordance:coyote` under **`Finishing Move.members`**.',
    '  - **Disambiguation (2-4):** Read player intent from the **whole** staged prop set plus candidate text. **`affordancesProvided` on staged props outranks** passive **`environmentAffordances`** on the contraption.',
    '',
    '- **Sub-step B - General promotion passes (bounded).** These rules implement **step 1** for intent-signal issues. One proportionate attempt per issue; if no legible fix, take **exit 3** (add to **`remainingPlanIssues`**) per the per-issue process --- do not emit a parallel "fixed in structure" story for the same issue.',
    '  - **`OUTLIER_PROP_UNACCOUNTED`:** If enrich mis-assigned trope and **candidate context + executionSummary** make a **better** trope slot **obvious**, promote the outlier into that trope `members` row (move `stableKey`, set `tropeFunction`). **Low** bar: obvious slot from skeleton + summary is enough. If no clear slot, **do not** force promotion.',
    '  - **`TROPE_FUNCTION_MISMATCH`:** If **`stableKey`** placement already matches the skeleton but the **`tropeFunction`** line disagrees with **`executionSummary`** / **`executionDetail`**, **rewrite `tropeFunction`** (and only that trope\'s **`executionDetail`** if needed for the same beat). **Do not** move `stableKey` between tropes here --- use outlier / structural rules for moves. If relabeling would pretend a use the candidate does not support, **pass through**.',
    '  - **`STRUCTURAL_CONTRADICTION` (one sub-type only):** **Plurality without commitment** --- multiple props compete for the **same trope role** without committing which fires. Reframe that trope\'s **`executionDetail`** so the competition reads as **intentional overbuilding** / optimism (Looney Tunes "more moving parts = more brilliance"). Example framings (adapt): Finishing Move: "A gauntlet of attacks"; Misdirection: "An obstacle course of dangers"; Bait: "An over-the-top spectacle of temptations"; Contraption: "A Rube Goldberg overengineered mess of optimistic causality"; Disadvantage: "A piling on of layered obstruction". If the contradiction is **not** this sub-type, **pass through**.',
    '  - **`DIRECTION_AMBIGUOUS`** / **`ROLE_CONFLICT`:** Use the per-issue process: **no** promotion attempt --- **step 3** only when still applicable; rubric reads them as underspecification.',
    '',
    '- **Postcondition self-check (before Phase 2; backstop).** After every issue for each materialized candidate is processed, verify: **no** issue is represented **both** in remediated **materialized** structure (**`tropeAssignments` / `members` / `outliers`**) **and** in **`remainingPlanIssues`**. If overlap exists, remediation applied in structure wins --- **remove** the duplicate from **`remainingPlanIssues`**. Primary enforcement is the per-issue branch; this is a consistency backstop.',
    '',
    '### Phase 2 - rubric judgment (internal mini-schema)',
    '- Build an internal `rubricJudgment` object:',
    '  `{ "candidateOrder": string[], "comparisons": { "<candidateId>": { "coverage": string, "completeness": string, "coherence": string } }, "tieBreak": string | null }`.',
    '- **Score `materializedCandidates` from Phase 1**, not the raw input block alone. Ground every dimension in the promoted rows and execution text **after** cleanup.',
    '- **Gimmick label:** Each candidate carries the input row\'s **`gimmick`** --- use it as the short funnel label when scoring so comparisons weight **spine + tropes**, not tropes alone.',
    '- **Finishing Move anchor:** For each candidate, treat **coverage**, **completeness**, and **coherence** as measuring how well the rest of the plan **supports the chosen Finishing Move** after materialization. **Name that finishing move** (or the materialized finishing mechanism) explicitly when it clarifies the sentence.',
    '- **Plurality / STRUCTURAL reframe:** If Phase 1 reframed plurality as deliberate overbuilding, treat that candidate\'s **coherence as strengthened** on its own terms --- **do not** penalize the same plurality again in Phase 2 (no double penalty).',
    '- Use this structure to support exactly one rubric sentence per candidate in **`## Rubric comparison`** (same order as input JSON).',
    '',
    '### Phase 3 - winner merge and residual issues (internal mini-schema)',
    '- Build an internal `winnerMerge` object:',
    '  `{ "winnerCandidateId": string, "paragraphSummaryDraft": string, "remainingPlanIssues": { "code": string, "summary": string, "evidence"?: string[] }[] }`.',
    '- **`remainingPlanIssues`** lists only issues cleanup **attempted** and **could not fully resolve**; drop resolved issues entirely (they appear nowhere). **`MISSING_FINISHING_MOVE`** is never listed here --- internal-only, always cleared before this object finalizes.',
    '',
    '### Phase 4 - final handoff emission',
    '- Emit required markdown sections in order (**## Materialized candidates (Phase 1)** through **`## Winner selection`**), then emit the final handoff `json` fence as the **last** fence in the response.',
    '- Ensure handoff JSON preserves required key types for `paragraphSummary` and `remainingPlanIssues` (see task section; parser maps to downstream `planIssues`).',
    '- Include `selectedCandidate` in the final handoff JSON anchored on the winning input candidate row',
    '  (`candidateId`, `gimmick`, `executionSummary`, `tropeAssignments`, `outliers`). Use the same **`candidateId`**, **`gimmick`**,',
    '  and **`executionSummary`** as the winner\'s input row (**reasoning alignment**: repeating **`gimmick`** locks your narrative to',
    '  that funnel; downstream code may normalize from combine if this echo is missing or mistyped). **`tropeAssignments`** must remain',
    '  a **non-array object keyed by trope** (matching the input shape);',
    '  do **not** rewrite it as an array. Preserve every staged-backed member and outlier row from the winning input;',
    '  **must** ensure **`Finishing Move`** is present with **>= 1** `members` row (add the trope block and/or `affordance:*` members per Phase 1).',
    `  you **may** append extra \`members\` rows whose \`stableKey\` uses the materialized prefix \`${MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX}\``,
    '  per the trope candidates JSON section (including FM-mandatory rows). Any trope key you emit must include valid',
    '  **`executionDetail`** and **`members`** arrays like the input tropes.',
] as const

const PLAN_SELECTION_INTERNAL_PHASES_SINGLE_CANDIDATE = [
    '## Internal phase order (single invocation; structured internals)',
    '- Keep one response, but execute these internal phases in order before finalizing output.',
    '- These phase artifacts are internal scaffolding for consistency and should not override output-format constraints.',
    '- The only **pipeline-consumed** artifact is the **final** trailing handoff **` ```json `** fence; Phase 1 materialization JSON is **visible scratchpad** you must write for reconciliation (see Task).',
    '- **Cleanup output vs wire naming.** Accumulate unresolved post-cleanup issues only in **`remainingPlanIssues`** during internal phases --- never build up something called **`planIssues`** for cleanup output. Input **`candidates[]`** rows do **not** carry a wire **`planIssues`** array.',
    '- **Internal vs wire.** You may build a full **materialized candidate** (including `affordance:*` synthetic `members` rows) for the **sole** input row. That materialized row exists **only inside this response** for rubric reasoning. It is **not** a second pipeline artifact. In the **trailing** handoff `json` fence, materialized `affordance:*` `members` appear **only** on **`selectedCandidate`** --- match the trope candidates JSON section.',
    '',
    '### Phase 1 - cleanup: materialized candidate set (internal mini-schema)',
    '- **Primary output:** `materializedCandidates` --- an array with **exactly one** fully materialized candidate object for the **sole** input `candidates[]` row, with the **same top-level shape** as that row: `candidateId`, `gimmick`, `executionSummary`, `tropeAssignments`, `outliers`. You **may** introduce a **`Finishing Move`** key under **`tropeAssignments`** when Sub-step A requires it (input rows may omit it).',
    `- **Goal:** For that option, **close resolvable gaps** so later scoring judges the plan at its **best achievable** form: promote affordance-backed staged props into the correct **trope** \`members\` rows (and add synthetic \`members\` whose \`stableKey\` uses the materialized prefix \`${MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX}\` when rules require), per the trope candidates JSON section.`,
    '- **Phase 1 is incomplete until written.** Emit this array as **real JSON** under **`## Materialized candidates (Phase 1)`** (Task section): one **` ```json `** block whose root object is **`{ "materializedCandidates": [ ... ] }`**. Phase 1 does **not** count as done until that fence exists. After it exists, treat it as the **source of truth** for candidate structure in Phase 2 / rubric --- do not reason from the raw input trope JSON alone.',
    '- **Soft verbosity caps** (prose only): after the Phase 1 JSON fence, keep per-candidate **annotation** bullets concise; at most **~12** non-empty bullets total across annotation lines; at most **one sentence** per `tropeAssignments[*].executionDetail` rewrite when you edit **prose** unless the trope candidates JSON already implies longer beat text. **Carve-out:** the Phase 1 **` ```json `** body (full **`materializedCandidates`** objects) is **exempt** from "avoid repeating JSON" --- you **must** emit complete rows there.',
    '',
    '- **Per-issue cleanup process (sequential; mutual exclusivity).** Cleanup walks **each identified issue** for that candidate **in order** (from skeleton audit and internal FM checks). For **each** issue, follow **exactly one** exit --- remediation success and **`remainingPlanIssues`** listing are **not** independent outputs:',
    '  1. **Attempt remediation** using the rule that matches the issue: **Sub-step A** (Finishing Move guarantee; internal `MISSING_FINISHING_MOVE` control-flow only), or **Sub-step B** (`OUTLIER_PROP_UNACCOUNTED` promotion, `TROPE_FUNCTION_MISMATCH` alignment, `STRUCTURAL_CONTRADICTION` plurality reframe), as appropriate.',
    '  2. **If remediation succeeds:** apply it to the **materialized** candidate and proceed to the **next** issue. The issue is **consumed** --- it must **not** appear in **`remainingPlanIssues`**, in markdown, or in any other field.',
    '  3. **If remediation does not succeed:** add the issue to **`remainingPlanIssues`** and proceed to the **next** issue. **No partial remediation:** do not apply a half-fix for that issue and also list it --- choose **exit 2** (full apply) or **exit 3** (list unresolved) only.',
    '  - **`DIRECTION_AMBIGUOUS`** / **`ROLE_CONFLICT`:** **Skip step 1** --- cleanup does not remediate underspecification. **Go directly to step 3** when the issue still applies.',
    '  - **Branching invariant:** There is **no** path that both applies a fix in materialized structure **and** lists the **same** gap in **`remainingPlanIssues`**. When **Sub-step A** materializes **Finishing Move**, that **consumes** internal `MISSING_FINISHING_MOVE` at step 2 --- it **never** reaches step 3 (no extra suppression rule needed).',
    '',
    '- **Sub-step A - Finishing Move guarantee (required).** Phase 2 rubric judgment and downstream hops anchor on **Finishing Move** as a known quantity. A candidate that reaches Phase 2 **without** a **`Finishing Move`** entry in **`tropeAssignments`** containing **at least one** `members` row is **incomplete**, not merely unenhanced --- it cannot be scored on the same basis as a complete candidate. **Satisfaction rule:** **`tropeAssignments` must include `Finishing Move`** with **`members` length >= 1**, each row either a staged prop or a synthetic `affordance:*` row added here. **Invalid shortcuts:** "Contraption implicitly delivers the finish," **`executionSummary`** alone, or harm implied in prose **without** that trope row **do not** satisfy the guarantee. **`MISSING_FINISHING_MOVE`** is internal control-flow for step 1 only --- **never** a **`code`** in **`remainingPlanIssues`**.',
    '  - Internal control-flow only (never wire, never handoff): you may note `MISSING_FINISHING_MOVE` **while** cleanup still owes a **Finishing Move** trope block with **>= 1** member; **always resolve** it before Phase 2 so it **never** appears in the trailing fence.',
    '  - **FM guarantee vs discretionary materialization:** The trope candidates JSON section limits *discretionary* synthetic rows. **This sub-step overrides** that limit for Finishing Move: additions required here are **mandatory**, even when they would not otherwise "clarify" the maneuver under the optional-row rule.',
    '  - **You may add** a new **`Finishing Move`** key to **`tropeAssignments`** when the input row omitted it (supply **`executionDetail`** plus **`members`** per trope shape).',
    '  - **Resolution priority** (first match wins; stop when **`tropeAssignments.Finishing Move.members` has >= 1 row): (1) Input already has **`Finishing Move`** with **>= 1** staged **member** --- done (may still edit text under Sub-step B). (2) **`affordancesProvided`** on any staged **member** or **outlier** clearly indicates a finishing mechanism --- materialize into **`Finishing Move.members`**. (3) Candidate context implies **Coyote-as-payload** --- materialize `affordance:coyote` (or suffixed variant) under **`Finishing Move.members`**. (4) A **Contraption** member\'s **`environmentAffordances`** lists **Finishing Move** in **roles** --- materialize from those env refs into **`Finishing Move.members`**. (5) **Fallback:** `affordance:coyote` under **`Finishing Move.members`**.',
    '  - **Disambiguation (2-4):** Read player intent from the **whole** staged prop set plus candidate text. **`affordancesProvided` on staged props outranks** passive **`environmentAffordances`** on the contraption.',
    '',
    '- **Sub-step B - General promotion passes (bounded).** These rules implement **step 1** for intent-signal issues. One proportionate attempt per issue; if no legible fix, take **exit 3** (add to **`remainingPlanIssues`**) per the per-issue process --- do not emit a parallel "fixed in structure" story for the same issue.',
    '  - **`OUTLIER_PROP_UNACCOUNTED`:** If enrich mis-assigned trope and **candidate context + executionSummary** make a **better** trope slot **obvious**, promote the outlier into that trope `members` row (move `stableKey`, set `tropeFunction`). **Low** bar: obvious slot from skeleton + summary is enough. If no clear slot, **do not** force promotion.',
    '  - **`TROPE_FUNCTION_MISMATCH`:** If **`stableKey`** placement already matches the skeleton but the **`tropeFunction`** line disagrees with **`executionSummary`** / **`executionDetail`**, **rewrite `tropeFunction`** (and only that trope\'s **`executionDetail`** if needed for the same beat). **Do not** move `stableKey` between tropes here --- use outlier / structural rules for moves. If relabeling would pretend a use the candidate does not support, **pass through**.',
    '  - **`STRUCTURAL_CONTRADICTION` (one sub-type only):** **Plurality without commitment** --- multiple props compete for the **same trope role** without committing which fires. Reframe that trope\'s **`executionDetail`** so the competition reads as **intentional overbuilding** / optimism (Looney Tunes "more moving parts = more brilliance"). Example framings (adapt): Finishing Move: "A gauntlet of attacks"; Misdirection: "An obstacle course of dangers"; Bait: "An over-the-top spectacle of temptations"; Contraption: "A Rube Goldberg overengineered mess of optimistic causality"; Disadvantage: "A piling on of layered obstruction". If the contradiction is **not** this sub-type, **pass through**.',
    '  - **`DIRECTION_AMBIGUOUS`** / **`ROLE_CONFLICT`:** Use the per-issue process: **no** promotion attempt --- **step 3** only when still applicable; rubric reads them as underspecification.',
    '',
    '- **Postcondition self-check (before Phase 2; backstop).** After every issue for each materialized candidate is processed, verify: **no** issue is represented **both** in remediated **materialized** structure (**`tropeAssignments` / `members` / `outliers`**) **and** in **`remainingPlanIssues`**. If overlap exists, remediation applied in structure wins --- **remove** the duplicate from **`remainingPlanIssues`**. Primary enforcement is the per-issue branch; this is a consistency backstop.',
    '',
    '### Phase 2 - rubric judgment (internal mini-schema)',
    '- Build an internal `rubricJudgment` object:',
    '  `{ "candidateOrder": string[], "comparisons": { "<candidateId>": { "coverage": string, "completeness": string, "coherence": string } }, "tieBreak": string | null }`.',
    '- **Non-comparative run:** `candidateOrder` has length **1**; `comparisons` has a **single** key (that sole **`candidateId`**); `tieBreak` is **`null`**.',
    '- **Score `materializedCandidates` from Phase 1**, not the raw input block alone. Ground every dimension in the promoted rows and execution text **after** cleanup.',
    '- **Gimmick label:** That candidate carries the input row\'s **`gimmick`** --- use it as the short funnel label when scoring.',
    '- **Finishing Move anchor:** Treat **coverage**, **completeness**, and **coherence** as measuring how well the rest of the plan **supports the chosen Finishing Move** after materialization. **Name that finishing move** (or the materialized finishing mechanism) explicitly when it clarifies the sentence.',
    '- **Plurality / STRUCTURAL reframe:** If Phase 1 reframed plurality as deliberate overbuilding, treat **coherence as strengthened** on this candidate\'s own terms --- **do not** penalize the same plurality again in Phase 2 (no double penalty).',
    '- Use this structure to support exactly one rubric sentence in **`## Rubric comparison`**, prefixed with the sole **`candidateId`**, **non-comparative** and grounded in the materialized row.',
    '',
    '### Phase 3 - winner merge and residual issues (internal mini-schema)',
    '- Build an internal `winnerMerge` object:',
    '  `{ "winnerCandidateId": string, "paragraphSummaryDraft": string, "remainingPlanIssues": { "code": string, "summary": string, "evidence"?: string[] }[] }`.',
    '- **`winnerCandidateId` must equal** the sole input **`candidateId`** --- there is no competing option and no tie-break.',
    '- **`remainingPlanIssues`** lists only issues cleanup **attempted** and **could not fully resolve**; drop resolved issues entirely. **`MISSING_FINISHING_MOVE`** is never listed here --- internal-only, always cleared before this object finalizes.',
    '',
    '### Phase 4 - final handoff emission',
    '- Emit required markdown sections in order (**## Materialized candidates (Phase 1)** through **`## Winner selection`**), then emit the final handoff `json` fence as the **last** fence in the response.',
    '- Ensure handoff JSON preserves required key types for `paragraphSummary` and `remainingPlanIssues` (see task section; parser maps to downstream `planIssues`).',
    '- Include `selectedCandidate` in the final handoff JSON anchored on the winning input candidate row',
    '  (`candidateId`, `gimmick`, `executionSummary`, `tropeAssignments`, `outliers`). Use the same **`candidateId`**, **`gimmick`**,',
    '  and **`executionSummary`** as the winner\'s input row (**reasoning alignment**: repeating **`gimmick`** locks your narrative to',
    '  that funnel; downstream code may normalize from combine if this echo is missing or mistyped). **`tropeAssignments`** must remain',
    '  a **non-array object keyed by trope** (matching the input shape);',
    '  do **not** rewrite it as an array. Preserve every staged-backed member and outlier row from the winning input;',
    '  **must** ensure **`Finishing Move`** is present with **>= 1** `members` row (add the trope block and/or `affordance:*` members per Phase 1).',
    `  you **may** append extra \`members\` rows whose \`stableKey\` uses the materialized prefix \`${MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX}\``,
    '  per the trope candidates JSON section (including FM-mandatory rows). Any trope key you emit must include valid',
    '  **`executionDetail`** and **`members`** arrays like the input tropes.',
] as const

const PLAN_SELECTION_TWO_JSON_FENCES_SECTION = [
    '## JSON fences (critical)',
    '- The **` ```json ` ** block in the **dynamic section below** (after seam rooms) is **input data**',
    '  --- read-only trope candidates.',
    '- You **may** emit **one** additional **` ```json ` ** fence **before** the standard Markdown sections',
    '  (see Task): **`## Materialized candidates (Phase 1)`** plus a single object with root **`materializedCandidates`**',
    '  --- Phase 1 scratchpad only; downstream code does **not** parse this fence.',
    '- Your reply must **end** with a **separate** **` ```json ` ** fenced block (language tag **json**)',
    '  containing the hop handoff keys --- that **final** fence is the **only** JSON the pipeline consumes.',
    '  **Do not** emit any **` ```json ` ** fence **after** that handoff fence.',
] as const

const PLAN_SELECTION_TASK_COMMON_SECTION_AND_HANDOFF = [
    '- Do **not** invent or rewrite candidate plans. Do not introduce **staged** props, rooms, trope beats,',
    '  or causal steps that are absent from the selected candidate\'s JSON fields (materialized affordance rows',
    '  are allowed only as specified in the trope candidates JSON section).',
    '- Then emit these sections **in order** (Phase 1 scratchpad first, then rubric sections, then handoff):',
    '  1. **`## Materialized candidates (Phase 1)`** --- required Phase 1 artifact. Immediately under this heading,',
    '     emit **one** **` ```json `** fenced block (language tag **json**) whose parsed root object is',
    '     **`{ "materializedCandidates": [ ... ] }`**: **exactly one** fully materialized candidate object per input',
    '     **`candidates[]`** row, **same order** as input, each object matching the input row shape (`candidateId`,',
    '     `gimmick`, `executionSummary`, `tropeAssignments`, `outliers`) after all promotions and mandatory **`Finishing Move`** /',
    `     \`${MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX}\` rows per internal Phase 1 rules.`,
    '     After that fence, add compact Markdown **cleanup trace** (bullets or subheadings by **`candidateId`**): for each',
    '     issue addressed while materializing that row, state the issue, what remediation was applied or why none, and',
    '     whether it was **consumed** (no **`remainingPlanIssues`** row) or **carried** to **`remainingPlanIssues`**. Do **not**',
    '     put this trace inside the JSON --- keep candidate rows identical to the combine shape.',
    '  2. **`## Intent conflicts`** --- list only evidence that the candidate may misread player',
    '     intent. Eligible: unaccounted staged props, affordance contradictions, **mismatches',
    '     between a member prop\'s `tropeFunction` and how the candidate uses that prop in `executionSummary`',
    '     or trope rows**, props central to the summary that never appear in members or outliers, and',
    '     topology issues for Road Runner positioning. Exclude execution risks, missing mechanisms, and',
    '     generic "might miss" failure concerns.',
    '- After **`## Winner selection`**, end your reply with **exactly one** trailing Markdown **` ```json ` ** fenced block (language tag **json**)',
    '  containing at least these required keys: **`',
    PLAN_SELECT_OUTPUT_JSON_KEYS.paragraphSummary,
    '`** (string: a restatement of the chosen candidate only; must start with `Selected',
    '  <candidateId>:` and stay anchored to that candidate\'s `executionSummary` plus listed',
    '  trope/member evidence --- no new plan steps) and **`',
    PLAN_SELECT_OUTPUT_JSON_KEYS.remainingPlanIssues,
    '`** (array: **only** issues that remain **unresolved** after cleanup; **omit** issues cleanup fully fixed --- they must not appear here or anywhere. Each row: **`code`**, **`summary`**, optional **`evidence`**. Allowed `code` values: `OUTLIER_PROP_UNACCOUNTED`,',
    '  `TROPE_FUNCTION_MISMATCH`, `STRUCTURAL_CONTRADICTION`, `DIRECTION_AMBIGUOUS`, `ROLE_CONFLICT`.',
    '  **Never** use `MISSING_FINISHING_MOVE` as a `code` (internal control-flow only).',
    '  Code semantics for v1: `OUTLIER_PROP_UNACCOUNTED`, `TROPE_FUNCTION_MISMATCH`, and',
    '  `STRUCTURAL_CONTRADICTION` are intent-signal evidence that should count against the winner in',
    '  your selection judgment; `DIRECTION_AMBIGUOUS` and `ROLE_CONFLICT` are underspecification',
    '  obligations for downstream deconfliction and are not automatic winner disqualifiers by',
    '  themselves.',
    '  **Do not** emit a **`planIssues`** key --- use **`remainingPlanIssues`** only; downstream code maps that field to `planIssues` outside this prompt.',
    '  Include **`',
    PLAN_SELECT_OUTPUT_JSON_KEYS.selectedCandidate,
    '`** derived from the winning input candidate (`candidateId`, `gimmick`, `executionSummary`, `tropeAssignments`, `outliers`).',
    '  Echo **`gimmick`** exactly as on that input row (**reasoning alignment** with the spine you scored; pipeline may normalize',
    '  from combine if omitted). Keep the same **`candidateId`**, **`executionSummary`**, and **trope-keyed object** shape as the winning row;',
    '  **Finishing Move** in **`tropeAssignments` is required for evaluation:** include a **`Finishing Move`** key with at least one `members` entry (staged and/or `affordance:*` from Phase 1) even when the input row omitted that trope.',
    '  preserve every staged-backed member and outlier row from input; you **may** append materialized-affordance',
    `  \`members\` rows (\`stableKey\` prefix \`${MATERIALIZED_AFFORDANCE_STABLE_KEY_PREFIX}\`) per the JSON section above (including FM-mandatory rows).`,
    '  **`tropeAssignments`** must remain a **non-array object keyed by trope**; do **not** reshape it as an array.',
    '  Treat **`selectedCandidate`** as required output for this prompt run; do not omit it unless generating it is impossible.',
    '  Additional keys are allowed, but **`paragraphSummary`**, **`remainingPlanIssues`**, and **`selectedCandidate`** must be present and well-typed.',
    '- The **final** **` ```json ` ** block in your entire output must be this **handoff** fence ---',
    '  the **last** fence in your output.',
] as const

const PLAN_SELECTION_INTRO_MULTI_CANDIDATE = [
    'You are **selecting** the best high-level Coyote-vs-Road-Runner maneuver from a **fixed list of',
    'candidates** (JSON below) before the detailed hypothesis is written. You are not asked to draft',
    'new candidate plans from scratch.',
    '',
    '## Perspective guardrail (hard constraint)',
    '- Evaluate and describe every candidate strictly from the Coyote\'s planning perspective.',
    '- Treat the Coyote as the sole planner and actor selecting maneuvers; the Road Runner is the',
    '  target to be affected by those maneuvers.',
    '- Describe each candidate as Coyote setup, intent, and Coyote-side failure-risk analysis where',
    '  relevant to the rubric.',
    '- Winner rationale should explain why the selected **provided candidate** best serves the',
    '  Coyote\'s maneuver.',
    '',
    ...PLAN_SELECTION_TWO_JSON_FENCES_SECTION,
    '',
    '## Task',
    '- Ground yourself briefly on the setup (at most one sentence before required sections).',
    '- **Cleanup first (internal):** follow Phase 1 to build **`materializedCandidates`**, then judge and compare in Phase 2 --- score each option at its **best achievable** form, not only its raw Stage One snapshot.',
    '- Compare **all listed candidates** under **coverage**, **completeness**, and **coherence** using',
    '  each row\'s fixed **`gimmick`**, **`candidateId`**, **`executionSummary`**, member **`tropeFunction`**, **`executionDetail`**, **`stableKey`**,',
    '  **`shortName`**, **`room`**, optional **`environmentAffordances`** / **`affordancesProvided`**, and',
    '  outlier membership as evidence. After you pick a winner, **`selectedCandidate`** must satisfy the Finishing Move guarantee;',
    '  rows added only for that guarantee are mandatory. Other discretionary synthetic rows still must trace to input fields.',
    '- In **`## Rubric comparison`**, write exactly one sentence per candidate in the same order as',
    '  input JSON. Every sentence must begin with **`candidateId`** (for example,',
    '  `candidate-2:`) and must stay grounded in that candidate\'s fields only.',
    '- Treat **coverage**, **completeness**, and **coherence** as **equally important** when judging',
    '  candidates. Do not emphasize one dimension over another in prose or tie-break language.',
    '- Do **not** grade or bias candidates on Road Runner safety, villain effectiveness, or outcome',
    '  comedy --- those belong to later execution prompts, not this rubric.',
    ...PLAN_SELECTION_TASK_COMMON_SECTION_AND_HANDOFF,
    '  3. **`## Rubric comparison`** --- exactly one sentence per candidate, each sentence prefixed',
    '     by that sentence\'s **`candidateId`**.',
    '  4. **`## Winner selection`** --- select exactly one best **candidate** by **`candidateId`** and',
    '     explain why using only winner-field evidence.',
    '- In **`## Winner selection`**, pick exactly **one** winning **`candidateId`** with no ties unless you',
    '  apply an explicit tie-break stated in one line (prefer avoiding ties).',
    '- The first line in **`## Winner selection`** must be exactly: **`Winner: <candidateId>`**.',
] as const

const PLAN_SELECTION_INTRO_SINGLE_CANDIDATE = [
    'You are **reviewing and refining** a single provided Coyote-vs-Road-Runner maneuver candidate',
    '(JSON below) before the detailed hypothesis is written. There is no candidate-to-candidate',
    'competition in this run.',
    '',
    '## Perspective guardrail (hard constraint)',
    '- Evaluate and describe the candidate strictly from the Coyote\'s planning perspective.',
    '- Treat the Coyote as the sole planner and actor selecting maneuvers; the Road Runner is the',
    '  target to be affected by those maneuvers.',
    '- Describe this candidate as Coyote setup, intent, and Coyote-side failure-risk analysis where',
    '  relevant to the rubric.',
    '',
    ...PLAN_SELECTION_TWO_JSON_FENCES_SECTION,
    '',
    '## Task',
    '- Ground yourself briefly on the setup (at most one sentence before required sections).',
    '- **Cleanup first (internal):** follow Phase 1 to build **`materializedCandidates`** (a **singleton** set for this run), then judge in Phase 2 --- score that option at its **best achievable** form, not only its raw Stage One snapshot.',
    '- Read **coverage**, **completeness**, and **coherence** for that candidate using **`gimmick`**, **`candidateId`**, **`executionSummary`**,',
    '  member **`tropeFunction`**, **`executionDetail`**, **`stableKey`**, **`shortName`**, **`room`**, optional',
    '  **`environmentAffordances`** / **`affordancesProvided`**, and outlier membership as evidence **after** cleanup.',
    '  **`selectedCandidate`** must satisfy the Finishing Move guarantee; mandatory FM synthetic rows still must trace to staged evidence per Phase 1.',
    '- In **`## Rubric comparison`**, write exactly one short sentence prefixed with the sole',
    '  **`candidateId`** (for example, `candidate-1:`). Keep it non-comparative and grounded only in',
    '  that candidate\'s fields.',
    ...PLAN_SELECTION_TASK_COMMON_SECTION_AND_HANDOFF,
    '  3. **`## Rubric comparison`** --- exactly one sentence prefixed by the sole **`candidateId`**.',
    '  4. **`## Winner selection`** --- select the sole **candidate** by **`candidateId`** and explain',
    '     why using only that candidate\'s field evidence.',
    '- In **`## Winner selection`**, the first line must be exactly: **`Winner: <candidateId>`**.',
] as const

export function buildPlanSelectPrompt(
    input: BuildPlanSelectPromptInput
): CoyotePromptParts {
    const isSingleCandidate = input.combined.candidates.length === 1
    const seamRoomMappingBlock = coyoteSeamRoomMappingLines(input.roomObjectsByRoom).join('\n')
    const tropeCandidatesJson = serializePlanSelectCandidateInput(input.combined, input.roomObjectsByRoom)
    const intro = isSingleCandidate
        ? PLAN_SELECTION_INTRO_SINGLE_CANDIDATE
        : PLAN_SELECTION_INTRO_MULTI_CANDIDATE
    const internalPhases = isSingleCandidate
        ? PLAN_SELECTION_INTERNAL_PHASES_SINGLE_CANDIDATE
        : PLAN_SELECTION_INTERNAL_PHASES_MULTI_CANDIDATE
    const invariantPrefix = [
        ...intro,
        '',
        '## Rubric dimensions',
        '- **coverage** --- how much each staged prop / affordance can contribute to the plan for that candidate\'s **`gimmick`** funnel;',
        '  **Finishing Move** rows',
        '  required by Phase 1 plus discretionary **`affordance:*`** rows you add (per the JSON section) count as explicit',
        '  affordance evidence when they trace to input **`environmentAffordances`**, **`affordancesProvided`**, or trope text.',
        '- **completeness** --- how much everything **needed** by the plan is already present or',
        '  constructable from staged props and topology (including synthesis implied by the plan).',
        '- **coherence** --- how well implied actions reinforce each other toward one maneuver.',
        '',
        ...PLAN_SELECT_COMBINED_JSON_SCHEMA_LINES,
        '',
        ...internalPhases,
        '',
        ...COYOTE_HYPOTHESIS_WORLD_TOPOLOGY_LINES,
        '',
        ...COYOTE_HYPOTHESIS_CARTOON_OPPORTUNITY_LINES,
        '',
        ...PLAN_SELECTION_READING_RULES,
        '',
        'The following blocks are specific to this request (seam room labels, then trope candidates JSON).',
    ].join('\n')

    const dynamicSuffix = [
        '',
        seamRoomMappingBlock,
        '',
        '## Trope candidates (input JSON)',
        '',
        '```json',
        tropeCandidatesJson,
        '```',
        '',
    ].join('\n')

    return {
        invariantPrefix,
        dynamicSuffix: `\n${dynamicSuffix}`,
    }
}
