// AUTOGENERATED FILE
// This file was generated from wmlQuery.ohm by `ohm generateBundles`.

import {
  ActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface WMLQuerySelectorActionDict<T> extends ActionDict<T> {
  WMLQueryContents?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  WMLLegalTag?: (this: NonterminalNode, arg0: TerminalNode) => T;
  TagAncestry?: (this: NonterminalNode, arg0: IterationNode) => T;
}

export interface WMLQuerySelectorSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
}

export interface WMLQuerySelectorGrammar extends Grammar {
  createSemantics(): WMLQuerySelectorSemantics;
  extendSemantics(superSemantics: WMLQuerySelectorSemantics): WMLQuerySelectorSemantics;
}

declare const grammar: WMLQuerySelectorGrammar;
export default grammar;

