// AUTOGENERATED FILE
// This file was generated from wmlQuery.ohm by `ohm generateBundles`.

import {
  ActionDict,
  Grammar,
  IterationNode,
  Node,
  NonterminalNode,
  Semantics,
  TerminalNode
} from 'ohm-js';

export interface WMLQuerySelectorActionDict<T> extends ActionDict<T> {
  WMLQueryContents?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  wmlLegalTag?: (this: NonterminalNode, arg0: TerminalNode) => T;
  stringText?: (this: NonterminalNode, arg0: IterationNode) => T;
  legalProperties?: (this: NonterminalNode, arg0: TerminalNode) => T;
  propertyEqualityFilter?: (this: NonterminalNode, arg0: IterationNode, arg1: NonterminalNode, arg2: IterationNode, arg3: TerminalNode, arg4: NonterminalNode, arg5: TerminalNode) => T;
  propertyFilter?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  firstFilter?: (this: NonterminalNode, arg0: TerminalNode) => T;
  nthChildFilter?: (this: NonterminalNode, arg0: TerminalNode, arg1: IterationNode, arg2: TerminalNode) => T;
  matchComponent?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  matchPredicate?: (this: NonterminalNode, arg0: IterationNode) => T;
  MatchFlatItem?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  MatchFlatList?: (this: NonterminalNode, arg0: IterationNode) => T;
  MatchGroup?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode, arg2: TerminalNode) => T;
  MatchOr?: (this: NonterminalNode, arg0: NonterminalNode, arg1: IterationNode) => T;
  MatchOrClause?: (this: NonterminalNode, arg0: TerminalNode, arg1: NonterminalNode) => T;
  MatchAncestry?: (this: NonterminalNode, arg0: NonterminalNode) => T;
  whitespace_verticalTab?: (this: NonterminalNode, arg0: TerminalNode) => T;
  whitespace_formFeed?: (this: NonterminalNode, arg0: TerminalNode) => T;
  whitespace_noBreakSpace?: (this: NonterminalNode, arg0: TerminalNode) => T;
  whitespace_byteOrderMark?: (this: NonterminalNode, arg0: TerminalNode) => T;
  whitespace?: (this: NonterminalNode, arg0: NonterminalNode | TerminalNode) => T;
}

export interface WMLQuerySelectorSemantics extends Semantics {
  addOperation<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
  extendOperation<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
  addAttribute<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
  extendAttribute<T>(name: string, actionDict: WMLQuerySelectorActionDict<T>): this;
}

export interface WMLQuerySelectorGrammar extends Grammar {
  createSemantics(): WMLQuerySelectorSemantics;
  extendSemantics(superSemantics: WMLQuerySelectorSemantics): WMLQuerySelectorSemantics;
}

declare const grammar: WMLQuerySelectorGrammar;
export default grammar;

